# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=255)),
            ],
        ),
    ]
