# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20170310_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='donor',
            field=models.BooleanField(default=False),
        ),
    ]
